name: dart_hydrologis_utils
description: Common dart utilities lib for our projects.
version: 0.6.1
repository: https://github.com/moovida/dart_hydrologis_utils
issue_tracker: https://github.com/moovida/dart_hydrologis_utils/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # BSD
  # timezone: ^0.5.7
  # BSD
  intl: '>=0.16.1 <=0.17.0'
  # Apache 2.0
  image: ^3.2.0
  path: ^1.8.2

  # MIT
  xml: ^6.1.0 #xml: '>=4.3.0 <=5.1.2'



dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
